<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2022-06-24 13:14:52',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2023-09-21 20:54:56',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 1,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2021-08-07 20:59:55',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 29,
                'order' => 3,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2024-06-11 23:53:44',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2021-08-07 20:12:22',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2021-08-07 20:12:22',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2021-08-07 20:12:22',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2021-08-07 20:12:22',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2021-08-07 18:52:09',
                'updated_at' => '2024-08-09 14:43:25',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Attachments',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paperclip',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-08-07 20:16:55',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => 'voyager.attachments.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Post Comments',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bubble',
                'color' => NULL,
                'parent_id' => 28,
                'order' => 2,
                'created_at' => '2021-08-07 20:20:55',
                'updated_at' => '2023-04-14 14:30:37',
                'route' => 'voyager.post-comments.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 28,
                'order' => 1,
                'created_at' => '2021-08-07 20:22:37',
                'updated_at' => '2021-08-07 20:58:22',
                'route' => 'voyager.user-posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Subscriptions',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2021-08-07 20:25:32',
                'updated_at' => '2021-08-07 20:55:55',
                'route' => 'voyager.subscriptions.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Transactions',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dollar',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2021-08-07 20:26:33',
                'updated_at' => '2021-08-07 20:55:55',
                'route' => 'voyager.transactions.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'User Bookmarks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bookmark',
                'color' => NULL,
                'parent_id' => 28,
                'order' => 3,
                'created_at' => '2021-08-07 20:27:47',
                'updated_at' => '2023-04-14 14:30:37',
                'route' => 'voyager.user-bookmarks.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Money',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dollar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2021-08-07 20:55:37',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2021-08-07 20:58:37',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Countries',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-location',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 2,
                'created_at' => '2021-09-21 18:10:16',
                'updated_at' => '2021-09-30 11:26:53',
                'route' => 'voyager.countries.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Taxes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-card',
                'color' => '#000000',
                'parent_id' => 33,
                'order' => 1,
                'created_at' => '2021-09-21 18:11:55',
                'updated_at' => '2021-09-30 11:26:53',
                'route' => 'voyager.taxes.index',
                'parameters' => 'null',
            ),
            19 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Public Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2021-09-29 19:43:27',
                'updated_at' => '2024-08-09 14:43:27',
                'route' => 'voyager.custom-pages.index',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Taxes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-card',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2021-09-30 11:25:21',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Identity Checks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-check',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 2,
                'created_at' => '2021-10-20 16:11:44',
                'updated_at' => '2024-03-27 13:12:25',
                'route' => 'voyager.user-verifies.index',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'User Reports',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-eye',
                'color' => '#000000',
                'parent_id' => 29,
                'order' => 4,
                'created_at' => '2021-11-05 11:32:40',
                'updated_at' => '2024-06-11 23:53:44',
                'route' => 'voyager.user-reports.index',
                'parameters' => 'null',
            ),
            23 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Contact Messages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2021-11-19 18:11:34',
                'updated_at' => '2024-08-09 14:43:27',
                'route' => 'voyager.contact-messages.index',
                'parameters' => 'null',
            ),
            24 => 
            array (
                'id' => 39,
                'menu_id' => 1,
                'title' => 'Invoices',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-receipt',
                'color' => NULL,
                'parent_id' => 27,
                'order' => 3,
                'created_at' => '2022-08-04 19:06:47',
                'updated_at' => '2024-03-27 13:12:18',
                'route' => 'voyager.invoices.index',
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Plans',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2023-04-18 14:19:18',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => 'voyager.plans.index',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Jobs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-archive',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2023-07-25 15:44:36',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 43,
                'menu_id' => 1,
                'title' => 'Companies',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2023-07-25 16:22:32',
                'updated_at' => '2024-06-11 23:53:46',
                'route' => 'voyager.companies.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Applicants Ranges',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 41,
                'order' => 4,
                'created_at' => '2023-07-25 16:23:29',
                'updated_at' => '2024-03-27 13:12:25',
                'route' => 'voyager.applicants-ranges.index',
                'parameters' => 'null',
            ),
            29 => 
            array (
                'id' => 45,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 41,
                'order' => 2,
                'created_at' => '2023-07-25 16:24:09',
                'updated_at' => '2024-03-27 13:12:27',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 47,
                'menu_id' => 1,
                'title' => 'Job Skills',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => 41,
                'order' => 7,
                'created_at' => '2023-07-25 19:39:23',
                'updated_at' => '2024-03-27 13:12:25',
                'route' => 'voyager.job-skills.index',
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 48,
                'menu_id' => 1,
                'title' => 'Job Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => NULL,
                'parent_id' => 41,
                'order' => 6,
                'created_at' => '2023-07-25 19:44:04',
                'updated_at' => '2024-03-27 13:12:25',
                'route' => 'voyager.job-types.index',
                'parameters' => NULL,
            ),
            32 => 
            array (
                'id' => 49,
                'menu_id' => 1,
                'title' => 'Skills',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-javascript',
                'color' => NULL,
                'parent_id' => 41,
                'order' => 3,
                'created_at' => '2023-07-25 20:35:17',
                'updated_at' => '2024-03-27 13:12:25',
                'route' => 'voyager.skills.index',
                'parameters' => NULL,
            ),
            33 => 
            array (
                'id' => 50,
                'menu_id' => 1,
                'title' => 'Newsletter Emails',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2023-07-25 20:42:04',
                'updated_at' => '2024-08-09 14:43:25',
                'route' => 'voyager.newsletter-emails.index',
                'parameters' => NULL,
            ),
            34 => 
            array (
                'id' => 51,
                'menu_id' => 1,
                'title' => 'Salary Ranges',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dollar',
                'color' => NULL,
                'parent_id' => 41,
                'order' => 5,
                'created_at' => '2023-07-25 20:47:50',
                'updated_at' => '2024-03-27 13:12:25',
                'route' => 'voyager.salary-ranges.index',
                'parameters' => NULL,
            ),
            35 => 
            array (
                'id' => 54,
                'menu_id' => 1,
                'title' => 'Featured Clients',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-star',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2023-09-25 20:40:18',
                'updated_at' => '2024-08-09 14:43:25',
                'route' => 'voyager.featured-clients.index',
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 55,
                'menu_id' => 1,
                'title' => 'Featured Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-rocket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2023-09-25 20:57:29',
                'updated_at' => '2024-08-09 14:43:27',
                'route' => 'voyager.featured-categories.index',
                'parameters' => NULL,
            ),
            37 => 
            array (
                'id' => 56,
                'menu_id' => 1,
                'title' => 'Jobs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => NULL,
                'parent_id' => 41,
                'order' => 1,
                'created_at' => '2024-03-27 13:12:01',
                'updated_at' => '2024-03-27 13:12:27',
                'route' => 'voyager.jobs.index',
                'parameters' => NULL,
            ),
            38 => 
            array (
                'id' => 57,
                'menu_id' => 1,
                'title' => 'Blog',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-documentation',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2024-06-11 23:17:40',
                'updated_at' => '2024-08-09 14:43:27',
                'route' => 'voyager.blog-posts.index',
                'parameters' => 'null',
            ),
            39 => 
            array (
                'id' => 60,
                'menu_id' => 1,
                'title' => 'Announcements',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-megaphone',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2024-08-07 17:27:57',
                'updated_at' => '2024-08-09 14:43:27',
                'route' => 'voyager.global-announcements.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}